name: Publish

on:
  push:
    branches: ['main']

permissions: write-all

jobs:
  qemu:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest, macos-14]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: "Setup Rust"
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: nightly
          components: clippy
      - name: Install dependencies
        run: npm install
      - name: Publish binaries
        run: npm run upload-binary
        env:
          NODE_PRE_GYP_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}